package com.scms.dao;

/**
 * Created by xieding001 on 2017/8/29.
 */

import com.scms.model.Channel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.repository.CrudRepository;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.List;

/**
 * 基础数据库操作类
 *
 * @author ss
 *
 */
public class BaseDao<T> {
    @Autowired // This means to get the bean called userRepository
    //  Which is auto-generated by Spring, we will use it to handle the data
    private CrudRepository crudRepository;




}

